### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by lucasleon2107** [redis/redis-om-spring#250] opened 2023-05-20 09:37 UTC
I using Spring Boot (3.0.2) with JDK 17, Kotlin (1.8.20) and the latest version of Redis OM (0.8.2). I configured the annotation processor using kapt. Here's the snippet:

```
<plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>kapt</id>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>src/main/kotlin</sourceDir>
                            </sourceDirs>
                            <annotationProcessorPaths>
                                <annotationProcessorPath>
                                    <groupId>com.redis.om</groupId>
                                    <artifactId>redis-om-spring</artifactId>
                                    <version>0.8.0</version>
                                </annotationProcessorPath>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <args>
                        <arg>-Xjsr305=strict</arg>
                    </args>
                    <compilerPlugins>
                        <plugin>spring</plugin>
                    </compilerPlugins>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

```

This is the class that is being generated:

```
public final class UserInfoHash$ {
  public static MetamodelField<UserInfoHash, String> _KEY;

  static {
    try {
      _KEY = new MetamodelField<UserInfoHash, String>("__key", String.class, true);
    } catch(NoSuchFieldException | SecurityException e) {
      System.err.println(e.getMessage());
    }
  }
}
```

But I'm getting the following error:
`exception java.lang.NoSuchFieldException is never thrown in body of corresponding try statement
`

**Comment by bsbodden** [comment] 2023-05-20 11:12
Lucas can you post the code for the `UserInfoHash` - I think I see what the problem is. I'm assuming that there will be other fields besides the `id`. But please post the code or similar code so that I can confirm.

**Comment by lucasleon2107** [comment] 2023-05-20 20:22
Sorry, I'm not near my computer right now, but it's a User data class with the @Document annotation, a String @Id that I'm setting myself, not autogenerated. Name and last name with @Searchable and a code String field with @Indexed. I hope that helps

**Comment by lucasleon2107** [comment] 2023-05-20 23:57
This is the class

```
@Document
data class UserInfoHash(
    @Id
    val accountId: String = "",
    @Searchable
    val firstName: String? = null,
    @Searchable
    val lastName: String? = null,
    @Indexed
    val code: String? = null
)
```

**Comment by lucasleon2107** [comment] 2023-05-23 00:09
@bsbodden any updates?

**Comment by bsbodden** [comment] 2023-05-23 05:00
Not yet, there hasn't been much testing for Kotlin so I'm in the process of building some tests.

**Comment by lucasleon2107** [comment] 2023-05-23 05:11
@bsbodden is there a way that I can make a query by multiple optional query params? I want to filter by name or last name and maybe other additional fields that I could add that will come from the controller

**Comment by lucasleon2107** [comment] 2023-05-23 09:11
@bsbodden I assume I have to use Predicates. Can you show me an example of how to achieve that?

**Comment by bsbodden** [comment] 2023-05-23 15:02
> @bsbodden is there a way that I can make a query by multiple optional query params? I want to filter by name or last name and maybe other additional fields that I could add that will come from the controller

Lucas, stop by our discord server and I can help you there. On the issue on this page, it looks like we might need to use the "all open plugin" and make modifications to OM to support Kotlin  https://kotlinlang.org/docs/all-open-plugin.html#maven 

So in the meantime, unfortunately, I would assume that there is no Kotlin support until announced. I'm building a comprehensive test suite to validate the Kotlin support and I would expect it out in 0.8.4 or so.

**Comment by bsbodden** [comment] 2023-05-24 02:16
@lucasleon2107 I think I have a running example working now. It was just a matter of getting kapt to behave correctly. I will post a link to a sample repo later today.

**Comment by bsbodden** [comment] 2023-05-24 05:09
@lucasleon2107 see https://github.com/redis-developer/redis-om-spring-kotlin-skeleton-app

**Comment by lucasleon2107** [comment] 2023-05-24 05:14
@bsbodden This great, thanks! I'll try it later today. I have a question. Do you have an example of how to make queries with the Java Predicate class? I did some tests, but they currently didn't work for me

**Comment by bsbodden** [comment] 2023-05-24 05:27
There are some examples on that repo.

**Comment by lucasleon2107** [comment] 2023-05-24 06:33
@bsbodden I tested the repo you posted, and unfortunately, it's not working for me. I also tried copying the kapt configuration, and it's not working on my project either, and I get two different errors on both projects. Mine keeps throwing `exception java.lang.NoSuchFieldException is never thrown in body of corresponding try statement` and with yours, I get 
```
cannot find symbol
[ERROR]   symbol:   class Person
[ERROR]   location: class com.redis.om.skeleton.models.Person$
```

**Comment by lucasleon2107** [comment] 2023-05-24 08:30
I made a change in the `kotlin-maven-plugin` . I removed `<extensions>true</extensions>` and added this to the execution:
```
<goals>
    <goal>kapt</goal>
</goals>
```
I'm still getting the `cannot find symbol` error, but at least the metamodel is generated without causing issues. Also, I just noticed that I needed to set all fields as `var` to get all the fields generated in the metamodel. I'll continue my tests and let you know if I find any more issues.

**Comment by lucasleon2107** [comment] 2023-05-24 10:06
I tested the `findByFirstNameAndLastName` method in your repo by sending null parameters, and I got this error: 
```
Cannot invoke "Object.getClass()" because "maybeText" is null
```

In my case that I'm doing queries with `contains` I get this error when sending a null param:
```
Error details: Cannot invoke "Object.toString()" because the return value of "com.redis.om.spring.search.stream.predicates.fulltext.LikePredicate.getValue()" is null
```

**Comment by lucasleon2107** [comment] 2023-05-24 15:33
@bsbodden, is there a way to bypass those errors with the current version?

**Comment by lucasleon2107** [comment] 2023-05-24 22:18
Hey @bsbodden, could you help me by sharing a code snippet illustrating how to implement filtering based on optional query parameters? It would be great if the snippet were compatible with the current version. Thanks!

**Comment by lucasleon2107** [comment] 2023-05-25 05:54
So I tried to achieve that with the `Example` class, but `RedisDocumentRepository` does not support it. Disappointing

**Comment by lucasleon2107** [comment] 2023-05-25 06:18
I understand, but I don't think this is a Kotlin issue. Does sending `null` for MetaModels predicates or sending just predicates work on Java?

**Comment by lucasleon2107** [comment] 2023-05-25 07:48
@bsbodden I achieved what I wanted by doing something like this:

```
suspend fun search(
        firstName: String? = null,
        lastName: String? = null,
        code: String? = null
    ): List<UserInfoHash> {
        var entityStream = entityStream.of(UserInfoHash::class.java)

        val predicates = mutableListOf<SearchFieldPredicate<UserInfoHash, String>>()

        code?.let {
            val predicate = `UserInfoHash $`.CODE.eq(code.uppercase())
            predicates.add(predicate)
        }

        firstName?.let {
            val predicate = `UserInfoHash$`.FIRST_NAME.containing(firstName.uppercase())
            predicates.add(predicate)
        }

        lastName?.let {
            val predicate = `UserInfoHash$`.LAST_NAME.containing(lastName.uppercase())
            predicates.add(predicate)
        }

        if (predicates.isNotEmpty()) {
            val combinedPredicates = combinePredicates(predicates)
            entityStream = entityStream.filter(combinedPredicates)
        }

        return entityStream.collect(Collectors.toList())
    }

    private fun <E, T> combinePredicates(predicates: List<SearchFieldPredicate<E, T>>): SearchFieldPredicate<E, T> {
        return object : SearchFieldPredicate<E, T> {
            override fun getSearchFieldType(): Schema.FieldType? {
                return null
            }

            override fun getField(): Field? {
                return null
            }

            override fun getSearchAlias(): String? {
                return null
            }

            override fun test(t: T): Boolean {
                return predicates.all { it.test(t) }
            }

            override fun apply(node: Node): Node {
                var currentNode = node
                for (predicate in predicates) {
                    currentNode = predicate.apply(currentNode)
                }
                return currentNode
            }
        }
    }
```

**Comment by bsbodden** [comment] 2023-05-25 17:54
* The null checks will be added to the Predicates that were missing, I think that should help a bit - this will be in v0.8.3-SNAPSHOT next publish. 
* RediSearch has a default minimum prefix set to 2, but you can change it globally using `FT.CONFIG SET MINPREFIX 1`
* If you get the Maven build to work correctly please send a PR, we could use the help!
* I'll take a look the predicate above to see if I can integrate it, after I get the null checking in place

**Comment by bsbodden** [comment] 2023-05-25 19:52
The issue is that the order should be:
- Generate sources (metamodels)
- Compile main sources
- Compile metamodels
This somehow happens in the right order with a regular Maven build using just Java, but it is out of order when using KAPT. I'll figure that out soon.

**Comment by lucasleon2107** [comment] 2023-05-25 19:54
Hi, I just fixed it by adding this plugin

```
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/kotlin</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by lucasleon2107** [comment] 2023-05-25 20:13
I already created the PR. Also, I ran `FT.CONFIG SET MINPREFIX 1`, but I'm still needed to send 3 characters or sometimes even 4 when doing a `containing` query

**Comment by bsbodden** [comment] 2023-05-26 04:24
In your example, you have:

```kotlin
code?.let {
    val predicate = `UserInfoHash $`.CODE.eq(code.uppercase())
    predicates.add(predicate)
}

firstName?.let {
    val predicate = `UserInfoHash$`.FIRST_NAME.containing(firstName.uppercase())
    predicates.add(predicate)
}

lastName?.let {
    val predicate = `UserInfoHash$`.LAST_NAME.containing(lastName.uppercase())
    predicates.add(predicate)
}
```

By adding the null checks and having the predicates be ignored if the params are null you can now do several chained `filter` commands where the params of the predicates could be null. This will `AND` the predicates. There is an `or` chaining method in Predicate that I haven't retrofitted to support this. So for now, only `AND` is supported.

Here's the PR https://github.com/redis/redis-om-spring/pull/251 - Once it's reviewed it should publish v`0.8.3-SNAPSHOT`

**Closed** 2023-05-26 15:04 UTC
Labels: enhancement

**Comment by lucasleon2107** [comment] 2023-07-13 06:13
Hi @bsbodden, I tried sending null values in the latest version (0.8.4), but it's still not working

**Comment by bsbodden** [comment] 2023-07-14 22:27
@lucasleon2107 can you modify the sample at https://github.com/redis-developer/redis-om-spring-kotlin-skeleton-app and add a reproducer. I'm working on adding a proper set of Kotlin specific tests to the redis-on repo.

**Comment by lucasleon2107** [comment] 2023-07-15 18:12
Hi @bsbodden, can you please provide more specifics about what do you need me to add to the repo?

**Comment by bsbodden** [comment] 2023-07-15 18:33
> Hi @bsbodden, can you please provide more specifics about what do you need me to add to the repo?

Maybe a quick test on the main app https://github.com/redis-developer/redis-om-spring-kotlin-skeleton-app/blob/main/src/main/kotlin/com/redis/om/skeleton/OmKotlinSkeletonApplication.kt to show the failure, modify the models as needed. I'll then add it to the Kotlin set of tests I'm making.

**Comment by lucasleon2107** [comment] 2023-07-16 10:51
Hi @bsbodden, I added a quick test on main. You can see that in this branch: https://github.com/lucasleon2107/redis-om-spring-kotlin-skeleton-app/tree/feature/test-null-filter-values

Also, I noticed that the generated Redis command for `contains` queries is: `%%%{query}%%%`. According to the [docs](https://redis.io/docs/interact/search-and-query/query/), this performs a fuzzy match, and I'm getting unexpected results. It seems that the correct command should be:  `*{query}*`
