### ISSUE TITLE
No attribute named messageListenerContainerRef found

### ISSUE THREAD

**Issue by artemrogov** [redis/redis-om-spring#102] opened 2022-09-04 20:17 UTC
Run application, see error:

Stack trace:
`java.lang.IllegalArgumentException: No attribute named messageListenerContainerRef found
	at org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.getAttribute(AnnotationRepositoryConfigurationSource.java:277) ~[spring-data-commons-2.7.2.jar:2.7.2]
	at org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.getAttribute(AnnotationRepositoryConfigurationSource.java:266) ~[spring-data-commons-2.7.2.jar:2.7.2]
	at org.springframework.data.redis.repository.configuration.RedisRepositoryConfigurationExtension.createRedisKeyValueAdapter(RedisRepositoryConfigurationExtension.java:152) ~[spring-data-redis-2.7.2.jar:2.7.2]
	at org.springframework.data.redis.repository.configuration.RedisRepositoryConfigurationExtension.lambda$registerBeansForRoot$4(RedisRepositoryConfigurationExtension.java:111) ~[spring-data-redis-2.7.2.jar:2.7.2]
	at org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport.registerIfNotAlreadyRegistered(RepositoryConfigurationExtensionSupport.java:231) ~[spring-data-commons-2.7.2.jar:2.7.2]
	at org.springframework.data.redis.repository.configuration.RedisRepositoryConfigurationExtension.registerBeansForRoot(RedisRepositoryConfigurationExtension.java:111) ~[spring-data-redis-2.7.2.jar:2.7.2]
	at org.springframework.data.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn(RepositoryConfigurationDelegate.java:136) ~[spring-data-commons-2.7.2.jar:2.7.2]
	at com.redis.om.spring.repository.configuration.RedisJSONRepositoriesRegistrar.registerBeanDefinitions(RedisJSONRepositoriesRegistrar.java:83) ~[redis-om-spring-0.5.1.jar:na]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396) ~[spring-context-5.3.22.jar:5.3.22]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[na:na]`

**Comment by sazzad16** [comment] 2022-09-04 23:08
Duplicate of #86

**Closed by sazzad16** 2022-09-04 23:08 UTC
