### ISSUE TITLE
Enable**Repositories annotation does not discover Models if not as part of main app

### ISSUE THREAD

**Issue by sergey-morenets** [redis/redis-om-spring#127] opened 2022-11-07 11:16 UTC
Hi

I tried to use search functionality:

```
public interface UserRepository 
		extends RedisDocumentRepository<User, Integer> {
	
	Optional<User> findByName(String name);
}
```

But when I call findByName method I receive an exception:
```

redis.clients.jedis.exceptions.JedisDataException: demo.model.UserIdx: no such index
	at redis.clients.jedis.Protocol.processError(Protocol.java:142) ~[jedis-3.8.0.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:176) ~[jedis-3.8.0.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:230) ~[jedis-3.8.0.jar:na]
```

My document:

```
@Getter
@Setter

@Document("users")
public class User {

	@Id
	private int id;

	@Indexed
	private String name;

	private int age;
}
```

And configuration:

```
@Configuration
@EnableRedisDocumentRepositories
public class RedisConfig {

}
```

**Comment by bsbodden** [comment] 2022-11-07 15:58
@sergey-morenets can you link to the full output of the spring-boot run command, also can you do that with an empty redis instance (flushall) and also do (on the redis-cli):
* `FT._LIST` and paste the output?
* `KEYS users:*`

Thanks

**Comment by sergey-morenets** [comment] 2022-11-07 18:39
Hi @bsbodden 

Yes, sure.

KEYS users:*

`(empty array)`

FT._LIST

`(empty array)`

Spring Boot output:

```
 :: Spring Boot ::                (v2.7.5)

2022-11-07 20:32:12.328  INFO 10924 --- [           main] demo.RedisJSONApplication                : Starting RedisJSONApplication using Java 19.0.1
2022-11-07 20:32:12.334  INFO 10924 --- [           main] demo.RedisJSONApplication                : No active profile set, falling back to 1 default profile: "default"
2022-11-07 20:32:12.831  INFO 10924 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2022-11-07 20:32:12.831  INFO 10924 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data RedisJSON repositories in DEFAULT mode.
2022-11-07 20:32:12.881  INFO 10924 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 34 ms. Found 1 RedisJSON repository interfaces.
2022-11-07 20:32:13.725  INFO 10924 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-11-07 20:32:13.734  INFO 10924 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-11-07 20:32:13.734  INFO 10924 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.68]
2022-11-07 20:32:13.826  INFO 10924 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-11-07 20:32:13.826  INFO 10924 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1440 ms
2022-11-07 20:32:14.388  INFO 10924 --- [           main] c.r.o.s.r.query.RediSearchQuery          : Creating findByName query method
2022-11-07 20:32:15.040  INFO 10924 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-11-07 20:32:15.048  INFO 10924 --- [           main] c.r.om.spring.RedisModulesConfiguration  : Creating Indexes......
2022-11-07 20:32:15.053  INFO 10924 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found 0 @Document annotated Beans...
2022-11-07 20:32:15.055  INFO 10924 --- [           main] com.redis.om.spring.RediSearchIndexer    : Found 0 @RedisHash annotated Beans...
2022-11-07 20:32:15.058  INFO 10924 --- [           main] demo.RedisJSONApplication                : Started RedisJSONApplication in 3.126 seconds (JVM running for 3.77)
2022-11-07 20:32:39.803  INFO 10924 --- [nio-8080-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-11-07 20:32:39.804  INFO 10924 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-11-07 20:32:39.804  INFO 10924 --- [nio-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
```

**Comment by sergey-morenets** [comment] 2022-11-07 18:41
> Post the version of the library you're using

If you ask about Redis OM then it's the latest one (0.6.2)

**Comment by bsbodden** [comment] 2022-11-07 20:26
@sergey-morenets it looks like it is not finding the class with the `@Document` annotation based on:
```
Found 0 @Document annotated Beans
```

There is something it doesn't like about your `User` class. Maybe try to fully qualify the `@EnableDocumentRepositories` like:
```
@EnableRedisDocumentRepositories(basePackages = {"the.package.where.User.is.located"})
```

**Comment by sergey-morenets** [comment] 2022-11-08 07:26
@bsbodden 

No, the message is wrong, User class with @Document annotation was found, because save method was executed correctly:

`repository.save(user);`

And data were persisted in Redis. I can create sample project to reproduce the issue.

**Comment by sergey-morenets** [comment] 2022-11-08 07:39
@bsbodden I added the sample project: https://github.com/sergey-morenets/redis

**Comment by mathuamos** [comment] 2022-11-08 16:57
> > Post the version of the library you're using
> 
> If you ask about Redis OM then it's the latest one (0.6.2)
I solved the issue by  degrading to version 0.60

**Comment by sergey-morenets** [comment] 2022-11-08 17:44
Thank you, @mathuamos 

So is it regression ?

**Comment by bsbodden** [comment] 2022-11-08 20:31
> @bsbodden
> 
> No, the message is wrong, User class with @document annotation was found, because save method was executed correctly:
> 
> `repository.save(user);`
> 
> And data were persisted in Redis. I can create sample project to reproduce the issue.

I was confused since your keys command came up empty for the collection prefix. If it is a regression, I'll release a patch version this weekend

**Comment by bsbodden** [comment] 2022-11-09 17:28
@sergey-morenets I'm trying your sample, I can make it work by changing the main app to:

```
@SpringBootApplication
@EnableRedisDocumentRepositories
public class RedisJSONApplication {
```

and removing the `RedisConfig`.  I will reword this ticket to reflect that it is a problem with external config to the main app. THanks!

**Comment by bsbodden** [comment] 2022-11-10 00:46
> Thank you, @mathuamos
> 
> So is it regression ?

No, the issue has been there all along. Configuration outside of the app just doesn't work. I'm researching what needs to be done to make it work.

**Comment by bsbodden** [comment] 2022-11-10 05:51
Should be resolved in https://s01.oss.sonatype.org/content/repositories/snapshots/com/redis/om/redis-om-spring/0.6.3-SNAPSHOT/

Could please try it?

**Closed** 2022-11-10 13:25 UTC
Labels: bug
