### ISSUE TITLE
Incorrect Document Type Returned by RedisDocumentRepository Query

### ISSUE THREAD

**Issue by Salman83** [redis/redis-om-spring#385] opened 2024-01-31 11:51 UTC
When using RedisDocumentRepository queries in my Spring Boot application with Redis OM, the repository is returning incorrect document types.

For example if I have two document classes: DocumentA and DocumentAB and using RedisDocumentRepository to query these 
documents as following :

`@Document("DocumentA")
public class DocumentA {

    @Indexed
    private Integer fieldX;

    @Indexed
    private Integer fieldY;

}`

`@Document("DocumentA_B")
public class DocumentAB {

    @Indexed
    private Integer fieldX;

    @Indexed
    private Integer fieldZ;

}`

`@Repository
public interface MyRepository extends RedisDocumentRepository<DocumentA, String> {

    List<DocumentA> findByFieldX(Integer value);

}`

When I use findByFieldXit returns documents of both types, even though I expect only DocumentA.
i.e.  findByFieldX returns list of DocumentA which contain data of both DocumentA and DocumentAB mapped to DocumentA ( with only fieldX)

Redis OM version: 0.8.7
Spring Boot version: 3.1.3
Redis server version: 

redis_version:7.2.3

redis_git_sha1:00000000

redis_build_id:3d14d12dce76b09b

redis_mode:standalone

os:Linux 3.10.0-1160.15.2.el7.x86_64 x86_64

**Comment by bsbodden** [comment] 2024-01-31 18:24
Can you post a small full-blown spring app to reproduce? Thanks

**Comment by Salman83** [comment] 2024-02-01 13:25
> Can you post a small full-blown spring app to reproduce? Thanks

Attached.
[test-redis-om-bug.zip](https://github.com/redis/redis-om-spring/files/14125898/test-redis-om-bug.zip)

**Comment by bsbodden** [comment] 2024-02-01 15:42
I see where the confusion lies... you have two entities `Person` and `PersonAddress` both of the are marked as `@Document`s. Which will create two different collections, search only works at a single collection label. That is queries/aggregations can't span different collections. 

So the assumption is that any nested fields become part of the same document, so when you do:
```java
PersonAddress address1 = new PersonAddress(1, "Address 1", "Somewhere Location1");
redisOmBugPersonRepository.save(new Person(1, "Person 1 Name", 20, address1));
```
That will create a single document with that just happens to have a `PersonAddress` document JSON at the node `address` and queries and aggregations on `PersonAddress` will only look at the embedded  doc

When you do:
```java
PersonAddress address1 = new PersonAddress(1, "Address 1", "Somewhere Location1");
redisOmBugAddressRepository.save(address1);
```
That also creates a standalone `PersonAddress` document in its own collection. 

To have two separate collections and associated them, providing a light-level of search capabilities between the two, there is an annotation to connect two collections via a field `@Reference` - here's an example of the use of `@Reference` in conjunction with `@Indexed`:

https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/City.java

```java
@Document("city")
public class City {
  @Id
  @NonNull
  private String id;

  @Reference
  @Indexed
  @NonNull
  private State state;
}
```
So in the case above, there are two collections `city` and `state` the `state` field in the JSON for `city` will have a reference , that is the value of the `id` field for a `state` standalone JSON object. In terms of searching you are limited by searching for `City` objects given a `State` object (under the covers the search is done by the `id` field)

https://github.com/redis/redis-om-spring/blob/main/redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ReferenceTest.java

In the future I might find ways to do more complex cross-collection queries using transactions/watches but that has a lot of complications with distribution/slots.

**Comment by Salman83** [comment] 2024-02-01 21:46
Thanks @bsbodden , but Am I missing something here because I'm already using @Reference 
and as I can see in the cache, Person collection have reference for the address.

![image](https://github.com/redis/redis-om-spring/assets/28825815/3cf8b836-7471-42e3-b180-f6b2b4c3538a)

And this is what I'm getting when calling getData

`[
    {
        "id": "01HNJD4KQRKRR6JBZHRFV0YFW4",
        "surId": 1,
        "name": "Address 1",
        "age": null,
        "address": null
    },
    {
        "id": "01HNJD4KYTNKJQNJPKHN9RN770",
        "surId": 2,
        "name": "Address 2",
        "age": null,
        "address": null
    },
    {
        "id": "01HNJD4KZJJ0MM51EYDF4CKX6C",
        "surId": 1,
        "name": "Person 1 Name",
        "age": 20,
        "address": {
            "id": "01HNJD4KQRKRR6JBZHRFV0YFW4",
            "surId": 1,
            "name": "Address 1",
            "location": "Somewhere Location1"
        }
    },
    {
        "id": "01HNJD4M3ZDTR8K60YECRACMC0",
        "surId": 1,
        "name": "Person 2 Name",
        "age": 30,
        "address": {
            "id": "01HNJD4KYTNKJQNJPKHN9RN770",
            "surId": 2,
            "name": "Address 2",
            "location": "Somewhere Location2"
        }
    }
]`

**Comment by Salman83** [comment] 2024-02-02 08:26
@bsbodden I think it has something to do with the documents name person and person_address.
because if I change the  @Document("person_address") to @Document("address") it works fine. so its like its doing wildcard when retrieving the data.

**Comment by bsbodden** [comment] 2024-02-04 16:43
@justTimTim do you have some cycles to look at this potential bug? Thanks!

**Comment by justTimTim** [comment] 2024-02-04 19:34
> @justTimTim do you have some cycles to look at this potential bug? Thanks!

This is not a bug, this is a feature)
The problem is not in the library, but in the very understanding of the word "prefix". Your two entities start with the same word, and if you search for something using a shorter prefix, radish will return all possible matches. For example, if in the current case you add another entity with the prefix “p”, then it will return both addresses and persons, since they will be collapsed by the prefix “p”.
@Salman83  Just make your prefix more unique and a bit like "PersonEntity"

**Comment by justTimTim** [comment] 2024-02-04 19:43
Perhaps the problem is that in the "@document" annotation the value should work as an alias for the index, and not add a prefix

**Comment by Salman83** [comment] 2024-02-05 05:22
> > @justTimTim do you have some cycles to look at this potential bug? Thanks!
> 
> This is not a bug, this is a feature) The problem is not in the library, but in the very understanding of the word "prefix". Your two entities start with the same word, and if you search for something using a shorter prefix, radish will return all possible matches. For example, if in the current case you add another entity with the prefix “p”, then it will return both addresses and persons, since they will be collapsed by the prefix “p”. @Salman83 Just make your prefix more unique and a bit like "PersonEntity"

Thanks,  In my opinion its not a feature in our scenario . I'm not directly searching for something here. The normal behavior or assumption is that when you specify a name for a collection its unique. who would guess that if you name document Person and another one PersonAddress  the data will be mixed on retrieval (using RedisDocumentRepository). 
 if it was me I would make the default behavior is searching and getting data for the exact collection name and maybe add some flag to override this behavior if needed.

**Comment by bsbodden** [comment] 2024-02-05 13:48
@Salman83 @justTimTim is right... In Redis Search indices are scoped to a prefix for the keys that they index. The prefix in OM by default is the name of the class, or the value passed to the annotations (`@Document` or `@RedisHash`). So it's a limitation in the naming of the collections based on the underlying `FT.CREATE` command. So, picking a different name for the child collection is the thing to do here.

**Comment by bsbodden** [comment] 2024-02-06 16:27
@Salman83 Thinking a bit more about this... Our auto-prefix generation relies on the `:` character when creating the index using `FT.CREATE`. So class `A` and class `B` get prefixes as `A:` and `B:` so in theory `DocumentA_B` and `DocumentA` as prefixes should contain `:` as a terminator. So just adding `DocumentA_B:` and `DocumentA:`  should fix your issues. You JSON or HASHES keys would look like `DocumentA:12345` and `DocumentA_B:54321` and there should be no collision/pollution of the indices

**Comment by bsbodden** [comment] 2024-02-06 16:28
We can also just enforce it and add `:` to any user-defined prefixes

**Comment by bsbodden** [comment] 2024-03-02 23:36
@Salman83 BTW, I just added code to enforce the `:` if not present in the prefix. Please test with `0.8.9` which will be release the week of March 4th

**Closed by bsbodden** 2024-03-02 23:36 UTC
Labels: bug
